name: CI/CD pipeline for flask deployment

# Where the pipeline is going to work -> branches
on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    setps:
      # ? Checkout code
      - name: Checkout python code
        uses: actions/checkout@v3
      # ? Set up python
      - name: Set up python app
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      # ? Install dependencies
      - name: Installing python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      # ? Linting
      - name: Run flake8 linting
        run: |
          source venv/bin/activate
          flake8 .  
      # ? Run test
      - name: Run tests cases for python app
        run: |
          source venv/bin/activate
          pytest test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      #? Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      # ? Log in to Docker hub
      - name: Log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # ? Build and push images
      - name: Push to Docker hub 
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/python-ci-cd-project .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/python-ci-cd-project:latest ${{ secrets.DOCKER_HUB_USERNAME }}/python-ci-cd-project:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/python-ci-cd-project:latest
      


